# Generated by Django 5.2.10 on 2026-02-27 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_tarea_tareanino'),
        ('core', '0002_usuarionino'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karaoke_completado', models.BooleanField(default=False)),
                ('juego_completado', models.BooleanField(default=False)),
                ('infografia_completado', models.BooleanField(default=False)),
                ('microhistoria_completado', models.BooleanField(default=False)),
                ('video_completado', models.BooleanField(default=False)),
                ('tareas_completado', models.BooleanField(default=False)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_secciones', to='core.usuarionino')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_ninos', to='books.section')),
            ],
            options={
                'verbose_name': 'Puntos por Sección',
                'verbose_name_plural': 'Puntos por Sección',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('nino', 'seccion')},
            },
        ),
    ]
