# Generated by Django 5.2.10 on 2026-02-26 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('core', '0002_usuarionino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de tarea en la sección')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('lectura', 'Lectura'), ('ejercicio', 'Ejercicio'), ('juego', 'Juego'), ('video', 'Video'), ('otro', 'Otro')], default='ejercicio', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='books.section')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['seccion', 'numero'],
                'unique_together': {('seccion', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='TareaNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_completadas', to='core.usuarionino')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completadas_por', to='books.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_ninos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea del Niño',
                'verbose_name_plural': 'Tareas de los Niños',
                'ordering': ['-fecha_completado', 'nino', 'tarea'],
                'unique_together': {('nino', 'tarea')},
            },
        ),
    ]
