# Generated by Django 5.2.10 on 2026-02-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_tarea_tareanino'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
