# Generated by Django 5.2.10 on 2026-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_section_fecha_fin_section_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='color_card',
            field=models.CharField(choices=[('azul', 'Azul'), ('violeta', 'Violeta'), ('verde', 'Verde'), ('naranja', 'Naranja'), ('rosa', 'Rosa'), ('turquesa', 'Turquesa'), ('indigo', 'Índigo'), ('rojo', 'Rojo')], default='azul', help_text='Color del gradiente de la tarjeta', max_length=20),
        ),
    ]
