# Generated by Django 5.2.10 on 2026-02-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_section_color_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='color_card',
            field=models.CharField(choices=[('azul', 'Azul'), ('violeta', 'Violeta'), ('verde', 'Verde'), ('naranja', 'Naranja'), ('rosa', 'Rosa'), ('turquesa', 'Turquesa'), ('indigo', 'Índigo'), ('rojo', 'Rojo'), ('blanco', 'Blanco')], default='azul', help_text='Color del gradiente de la tarjeta', max_length=20),
        ),
    ]
