from django.urls import path

from .views import (
    domingo1_microhistoria,
    domingo2_microhistoria,
    domingo3_microhistoria,
    domingo4_microhistoria,
    domingo2_canciones,
    domingo2_game,
    domingo2_karaoke,
    register_view,
    login_view,
    logout_view,
    home,
    landing,
    domingo1,
    domingo2,
    domingo3,
    domingo4,
    domingo1_game,
    domingo1_karaoke,
    dashboard,
    domingo1_infografia,
    domingo2_infografia,
    domingo3_infografia,
    domingo4_infografia,
    premium_dashboard,
    select_nino,
    seccion_tareas,
    toggle_tarea,
    registrar_actividad,
    domingo1_canciones
)

urlpatterns = [
    path('', landing, name='landing'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('home/', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/premium/', premium_dashboard, name='premium-dashboard'),
    path('select-nino/', select_nino, name='select-nino'),
    path('domingo/4/', domingo4, name='domingo4'),
    path('domingo/3/', domingo3, name='domingo3'),
    path('domingo/2/', domingo2, name='domingo2'),
    path('domingo/1/', domingo1, name='domingo1'),
    path('domingo/1/game', domingo1_game, name='domingo1-game'),
    path('domingo/1/karaoke', domingo1_karaoke, name='domingo1-karaoke'),
    path('domingo/1/infografia', domingo1_infografia, name='domingo1-infografia'),
    path('domingo/2/infografia', domingo2_infografia, name='domingo2-infografia'),
    path('domingo/3/infografia', domingo3_infografia, name='domingo3-infografia'),
    path('domingo/4/infografia', domingo4_infografia, name='domingo4-infografia'),
    path('domingo/2/canciones', domingo2_canciones, name='domingo2-canciones'),
    path('domingo/2/karaoke', domingo2_karaoke, name='domingo2-karaoke'),
    path('domingo/2/game', domingo2_game, name='domingo2-game'),

    path('domingo/1/microhistoria', domingo1_microhistoria, name='domingo1-microhistoria'),
    path('domingo/2/microhistoria', domingo2_microhistoria, name='domingo2-microhistoria'),
    path('domingo/3/microhistoria', domingo3_microhistoria, name='domingo3-microhistoria'),
    path('domingo/4/microhistoria', domingo4_microhistoria, name='domingo4-microhistoria'),
    path('domingo/1/canciones', domingo1_canciones, name='domingo1-canciones'),

    # Tareas
    path('seccion/<int:seccion_id>/tareas/', seccion_tareas, name='seccion-tareas'),
    path('tarea/<int:tarea_id>/toggle/', toggle_tarea, name='toggle-tarea'),
    path('domingo/<int:seccion_id>/actividad/<str:actividad>/', registrar_actividad, name='registrar-actividad'),

]
