from django.urls import path

from .views import (
    domingo1_microhistoria,
    domingo2_microhistoria,
    domingo3_microhistoria,
    domingo4_microhistoria,
    domingo5_microhistoria,
    domingo6_microhistoria,
    domingo7_microhistoria,
    domingo8_microhistoria,
    domingo9_microhistoria,
    domingo10_microhistoria,
    domingo11_microhistoria,
    domingo12_microhistoria,
    domingo13_microhistoria,
    domingo14_microhistoria,
    domingo15_microhistoria,
    



    domingo2_canciones,
    domingo2_game,

    register_view,
    login_view,
    logout_view,
    home,
    landing,
    domingo1,
    domingo2,
    domingo3,
    domingo4,
    domingo5,
    domingo6,
    domingo7,
    domingo8,
    domingo9,
    domingo10,
    domingo11,
    domingo12,
    domingo13,

    domingo14,
    domingo15,
    domingo16,
    domingo17,
    domingo18,
    domingo19,
    domingo20,
    domingo21,

    domingo22,
    domingo23,
    domingo24,
    domingo25,
    domingo26,
    domingo27,
    domingo28,
    domingo29,
    domingo30,

    domingo31,
    domingo32,
    domingo33,
    domingo34,
    domingo35,
    domingo36,
    domingo37,
    domingo38,


    domingo39,
    domingo40,
    domingo41,
    domingo42,

    domingo43,
    domingo44,
    domingo45,
    domingo46,

    domingo47,
    domingo48,
    domingo49,
    domingo50,
    domingo51,
    domingo52,
    
    domingo1_game,
    domingo1_karaoke,
    domingo2_karaoke,
    domingo3_karaoke,
    domingo4_karaoke,
    domingo5_karaoke,
    domingo6_karaoke,
    domingo7_karaoke,
    domingo8_karaoke,
    domingo9_karaoke,
    domingo10_karaoke,
    domingo11_karaoke,
    domingo12_karaoke,
    domingo13_karaoke,
    domingo14_karaoke,
    domingo15_karaoke,


    dashboard,


    domingo1_infografia,
    domingo2_infografia,
    domingo3_infografia,
    domingo4_infografia,
    domingo5_infografia,
    domingo6_infografia,
    domingo7_infografia,
    domingo8_infografia,
    domingo9_infografia,
    domingo10_infografia,
    domingo11_infografia,
    domingo12_infografia,
    domingo13_infografia,
    domingo14_infografia,
    domingo15_infografia,
    domingo16_infografia,
    domingo17_infografia,
    domingo18_infografia,
    domingo19_infografia,
    domingo20_infografia,
    domingo21_infografia,
    domingo22_infografia,
    domingo23_infografia,
    domingo24_infografia,
    domingo25_infografia,
    domingo26_infografia,
    domingo27_infografia,
    domingo28_infografia,
    domingo29_infografia,
    domingo30_infografia,
    domingo31_infografia,
    domingo32_infografia,
    domingo33_infografia,   
    domingo34_infografia,
    domingo35_infografia,
    domingo36_infografia,
    domingo37_infografia,
    domingo38_infografia,
    domingo39_infografia,
    domingo40_infografia,
    domingo41_infografia,

    domingo42_infografia,
    domingo43_infografia,
    domingo44_infografia,
    domingo45_infografia,
    domingo46_infografia,
    domingo47_infografia,
    domingo48_infografia,
    domingo49_infografia,
    domingo50_infografia,
    domingo51_infografia,
    domingo52_infografia,
    



    premium_dashboard,
    select_nino,
    seccion_tareas,
    toggle_tarea,
    registrar_actividad,
    domingo1_canciones
)

urlpatterns = [
    path('', landing, name='landing'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('home/', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/premium/', premium_dashboard, name='premium-dashboard'),
    path('select-nino/', select_nino, name='select-nino'),
    path('domingo/4/', domingo4, name='domingo4'),
    path('domingo/3/', domingo3, name='domingo3'),
    path('domingo/2/', domingo2, name='domingo2'),
    path('domingo/1/', domingo1, name='domingo1'),
    path('domingo/5/', domingo5, name='domingo5'),
    path('domingo/6/', domingo6, name='domingo6'),
    path('domingo/7/', domingo7, name='domingo7'),
    path('domingo/8/', domingo8, name='domingo8'),
    path('domingo/9/', domingo9, name='domingo9'),
    path('domingo/10/', domingo10, name='domingo10'),
    path('domingo/11/', domingo11, name='domingo11'),
    path('domingo/12/', domingo12, name='domingo12'),
    path('domingo/13/', domingo13, name='domingo13'),
    path('domingo/14/', domingo14, name='domingo14'),
    path('domingo/15/', domingo15, name='domingo15'),
    path('domingo/16/', domingo16, name='domingo16'),
    path('domingo/17/', domingo17, name='domingo17'),
    path('domingo/18/', domingo18, name='domingo18'),
    path('domingo/19/', domingo19, name='domingo19'),
    path('domingo/20/', domingo20, name='domingo20'),
    path('domingo/21/', domingo21, name='domingo21'),
    path('domingo/22/', domingo22, name='domingo22'),
    path('domingo/23/', domingo23, name='domingo23'),
    path('domingo/24/', domingo24, name='domingo24'),
    path('domingo/25/', domingo25, name='domingo25'),
    path('domingo/26/', domingo26, name='domingo26'),
    path('domingo/27/', domingo27, name='domingo27'),
    path('domingo/28/', domingo28, name='domingo28'),
    path('domingo/29/', domingo29, name='domingo29'),
    path('domingo/30/', domingo30, name='domingo30'),
    path('domingo/31/', domingo31, name='domingo31'),
    path('domingo/32/', domingo32, name='domingo32'),
    path('domingo/33/', domingo33, name='domingo33'),
    path('domingo/34/', domingo34, name='domingo34'),
    path('domingo/35/', domingo35, name='domingo35'),
    path('domingo/36/', domingo36, name='domingo36'),
    path('domingo/37/', domingo37, name='domingo37'),
    path('domingo/38/', domingo38, name='domingo38'),
    path('domingo/39/', domingo39, name='domingo39'),
    path('domingo/40/', domingo40, name='domingo40'),
    path('domingo/41/', domingo41, name='domingo41'),
    path('domingo/42/', domingo42, name='domingo42'),
    path('domingo/43/', domingo43, name='domingo43'),
    path('domingo/44/', domingo44, name='domingo44'),
    path('domingo/45/', domingo45, name='domingo45'),
    path('domingo/46/', domingo46, name='domingo46'),
    path('domingo/47/', domingo47, name='domingo47'),
    path('domingo/48/', domingo48, name='domingo48'),
    path('domingo/49/', domingo49, name='domingo49'),
    path('domingo/50/', domingo50, name='domingo50'),
    path('domingo/51/', domingo51, name='domingo51'),
    path('domingo/52/', domingo52, name='domingo52'),





    path('domingo/1/game', domingo1_game, name='domingo1-game'),
    path('domingo/1/karaoke', domingo1_karaoke, name='domingo1-karaoke1'),
    path('domingo/2/karaoke', domingo2_karaoke, name='domingo2-karaoke2'),
    path('domingo/3/karaoke', domingo3_karaoke, name='domingo3-karaoke3'),
    path('domingo/4/karaoke', domingo4_karaoke, name='domingo4-karaoke4'),
    path('domingo/5/karaoke', domingo5_karaoke, name='domingo5-karaoke5'),
    path('domingo/6/karaoke', domingo6_karaoke, name='domingo6-karaoke6'),
    path('domingo/7/karaoke', domingo7_karaoke, name='domingo7-karaoke7'),
    path('domingo/8/karaoke', domingo8_karaoke, name='domingo8-karaoke8'),
    path('domingo/9/karaoke', domingo9_karaoke, name='domingo9-karaoke9'),
    path('domingo/10/karaoke', domingo10_karaoke, name='domingo10-karaoke10'),
    path('domingo/11/karaoke', domingo11_karaoke, name='domingo11-karaoke11'),
    path('domingo/12/karaoke', domingo12_karaoke, name='domingo12-karaoke12'),
    path('domingo/13/karaoke', domingo13_karaoke, name='domingo 13-karaoke13'),
    path('domingo/14/karaoke', domingo14_karaoke, name='domingo 14-karaoke14'),
    path('domingo/15/karaoke', domingo15_karaoke, name='domingo 15-karaoke15'),

    path('domingo/1/infografia', domingo1_infografia, name='domingo1-infografia'),
    path('domingo/2/infografia', domingo2_infografia, name='domingo2-infografia'),
    path('domingo/3/infografia', domingo3_infografia, name='domingo3-infografia'),
    path('domingo/4/infografia', domingo4_infografia, name='domingo4-infografia'),
    path('domingo/5/infografia', domingo5_infografia, name='domingo5-infografia'),
    path('domingo/6/infografia', domingo6_infografia, name='domingo6-infografia'),
    path('domingo/7/infografia', domingo7_infografia, name='domingo7-infografia'),
    path('domingo/8/infografia', domingo8_infografia, name='domingo8-infografia'),
    path('domingo/9/infografia', domingo9_infografia, name='domingo9-infografia'),
    path('domingo/10/infografia', domingo10_infografia, name='domingo10-infografia'),
    path('domingo/11/infografia', domingo11_infografia, name='domingo11-infografia'),
    path('domingo/12/infografia', domingo12_infografia, name='domingo12-infografia'),
    path('domingo/13/infografia', domingo13_infografia, name='domingo13-infografia'),
    path('domingo/14/infografia', domingo14_infografia, name='domingo14-infografia'),
    path('domingo/15/infografia', domingo15_infografia, name='domingo15-infografia'),
    path('domingo/16/infografia', domingo16_infografia, name='domingo16-infografia'),
    path('domingo/17/infografia', domingo17_infografia, name='domingo17-infografia'),
    path('domingo/18/infografia', domingo18_infografia, name='domingo18-infografia'),
    path('domingo/19/infografia', domingo19_infografia, name='domingo19-infografia'),
    path('domingo/20/infografia', domingo20_infografia, name='domingo20-infografia'),
    path('domingo/21/infografia', domingo21_infografia, name='domingo21-infografia'),
    path('domingo/22/infografia', domingo22_infografia, name='domingo22-infografia'),
    path('domingo/23/infografia', domingo23_infografia, name='domingo23-infografia'),
    path('domingo/24/infografia', domingo24_infografia, name='domingo24-infografia'),
    path('domingo/25/infografia', domingo25_infografia, name='domingo25-infografia'),
    path('domingo/26/infografia', domingo26_infografia, name='domingo26-infografia'),
    path('domingo/27/infografia', domingo27_infografia, name='domingo27-infografia'),
    path('domingo/28/infografia', domingo28_infografia, name='domingo28-infografia'),
    path('domingo/29/infografia', domingo29_infografia, name='domingo29-infografia'),
    path('domingo/30/infografia', domingo30_infografia, name='domingo30-infografia'),
    path('domingo/31/infografia', domingo31_infografia, name='domingo31-infografia'),               
    path('domingo/32/infografia', domingo32_infografia, name='domingo32-infografia'),
    path('domingo/33/infografia', domingo33_infografia, name='domingo33-infografia'),
    path('domingo/34/infografia', domingo34_infografia, name='domingo34-infografia'),
    path('domingo/35/infografia', domingo35_infografia, name='domingo35-infografia'),
    path('domingo/36/infografia', domingo36_infografia, name='domingo36-infografia'),
    path('domingo/37/infografia', domingo37_infografia, name='domingo37-infografia'),
    path('domingo/38/infografia', domingo38_infografia, name='domingo38-infografia'),
    path('domingo/39/infografia', domingo39_infografia, name='domingo39-infografia'),
    path('domingo/40/infografia', domingo40_infografia, name='domingo40-infografia'),
    path('domingo/41/infografia', domingo41_infografia, name='domingo41-infografia'),
    path('domingo/42/infografia', domingo42_infografia, name='domingo42-infografia'),
    path('domingo/43/infografia', domingo43_infografia, name='domingo43-infografia'),
    path('domingo/44/infografia', domingo44_infografia, name='domingo44-infografia'),
    path('domingo/45/infografia', domingo45_infografia, name='domingo45-infografia'),
    path('domingo/46/infografia', domingo46_infografia, name='domingo46-infografia'),
    path('domingo/47/infografia', domingo47_infografia, name='domingo47-infografia'),
    path('domingo/48/infografia', domingo48_infografia, name='domingo48-infografia'),
    path('domingo/49/infografia', domingo49_infografia, name='domingo49-infografia'),
    path('domingo/50/infografia', domingo50_infografia, name='domingo50-infografia'),
    path('domingo/51/infografia', domingo51_infografia, name='domingo51-infografia'),
    path('domingo/52/infografia', domingo52_infografia, name='domingo52-infografia'),       


    path('domingo/2/canciones', domingo2_canciones, name='domingo2-canciones'),
    path('domingo/2/game', domingo2_game, name='domingo2-game'),

    path('domingo/1/microhistoria', domingo1_microhistoria, name='domingo1-microhistoria'),
    path('domingo/2/microhistoria', domingo2_microhistoria, name='domingo2-microhistoria'),
    path('domingo/3/microhistoria', domingo3_microhistoria, name='domingo3-microhistoria'),
    path('domingo/4/microhistoria', domingo4_microhistoria, name='domingo4-microhistoria'),
    path('domingo/5/microhistoria', domingo5_microhistoria, name='domingo5-microhistoria'),
    path('domingo/6/microhistoria', domingo6_microhistoria, name='domingo6-microhistoria'),
    path('domingo/7/microhistoria', domingo7_microhistoria, name='domingo7-microhistoria'),
    path('domingo/8/microhistoria', domingo8_microhistoria, name='domingo8-microhistoria'),
    path('domingo/9/microhistoria', domingo9_microhistoria, name='domingo9-microhistoria'),
    path('domingo/10/microhistoria', domingo10_microhistoria, name='domingo10-microhistoria'),
    path('domingo/11/microhistoria', domingo11_microhistoria, name='domingo11-microhistoria'),
    path('domingo/12/microhistoria', domingo12_microhistoria, name='domingo12-microhistoria'),
    path('domingo/13/microhistoria', domingo13_microhistoria, name='domingo13-microhistoria'),
    path('domingo/14/microhistoria', domingo14_microhistoria, name='domingo14-microhistoria'),     
    path('domingo/15/microhistoria', domingo15_microhistoria, name='domingo15-microhistoria'),


    # Tareas
    path('seccion/<int:seccion_id>/tareas/', seccion_tareas, name='seccion-tareas'),
    path('tarea/<int:tarea_id>/toggle/', toggle_tarea, name='toggle-tarea'),
    path('domingo/<int:seccion_id>/actividad/<str:actividad>/', registrar_actividad, name='registrar-actividad'),

]

